title: "Tony Jokiranta"
description: "Portfolio & Blog"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Show About & Projects in the nav (minima feature)
header_pages:
  - about.md
  - projects.md

# Nice blog URLs
permalink: /:title/
